name: 'RelativeCI agent'
description: 'Send webpack stats and CI build information to RelativeCI'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  webpackStatsFile:
    description: 'Path to your local webpack stats file'
    required: true
  key:
    description: 'RelativeCI project key'
    required: true
  slug:
    description: 'RelativeCI project slug'
    required: false
  debug:
    description: 'Output debug info'
    required: false
runs:
  using: "composite"
  steps:
    - name: Copy webpack stats file
      run: cp ${{ inputs.webpackStatsFile }} ${{ github.action_path}}/webpack-stats.json
      shell: bash

    - id: set-debug
      name: Set DEBUG environment variable
      env:
        INPUT_DEBUG: ${{ inputs.debug }}
      run: |
        RELATIVE_CI_DEBUG=$([ -z ${INPUT_DEBUG} ] && echo "" || echo "relative-ci:agent")
        echo "::set-output name=debug::${RELATIVE_CI_DEBUG}"
      shell: bash

    # Get commit message for cases where the build is triggered by a different commit
    # eg: pull_request
    - uses: actions/github-script@v4
      id: event-commit-message
      with:
        script: |
          if (context.eventName !== "pull_request") {
            return "";
          }

          let commitMessage;

          try {
            const res = await github.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });

            commitMessage = res.data.commit.message;
          } catch (_) {
            // noop
          }

          return commitMessage;

        result-encoding: string

    - run: |
        # Go to action directory
        cd ${{ github.action_path }}

        # Run @relative-ci/agent cli
        ./node_modules/@relative-ci/agent/bin/index.js --commit $COMMIT --branch $BRANCH --pr $PR --commit-message "${COMMIT_MESSAGE}"
      shell: bash
      env:
        RELATIVE_CI_KEY: ${{ inputs.key }}
        RELATIVE_CI_SLUG: ${{ inputs.slug }}
        DEBUG: ${{ steps.set-debug.outputs.debug }}
        COMMIT: ${{ github.ebent.pull_request.head.sha }}
        COMMIT_MESSAGE: ${{ steps.event-commit-message.outputs.result }}
        BRANCH: ${{ github.event.pull_request.head.ref }}
        PR: ${{ github.event.pull_request.number }}
