name: 'RelativeCI agent'
description: 'Send bundle stats and CI build information to RelativeCI'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  key:
    description: 'RelativeCI project API key'
    required: true
  token: 
    description: GitHub token
    required: false
  webpackStatsFile:
    description: 'Path to your local bundle stats file'
    required: false
  slug:
    description: 'RelativeCI project slug'
    required: false
  endpoint:
    description: 'RelativeCI ingest endpoint'
    required: false
  includeCommitMessage:
    description: 'Include commit message'
    required: false
    default: 'true'
  debug:
    description: 'Output debug info'
    required: false,
    default: 'false'
  artifactName:
    description: 'GitHub action artifact name to download when running in workflow_run'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
