import * as core from '@actions/core';

export const logger = {
  log: core.info,
  debug: core.debug,
  info: core.info,
  warn: core.warning,
  error: core.error,
};

type GetSummaryData = {
  title: string;
  url: string;
}

export function getSummary({ title, url }: GetSummaryData): string {
  const output = [
    `## ${title}`,
    `[View bundle analysis report](${url}?utm_source=github&utm_campaign=github-action-summary)`,
    '---',
    `<sup>Generated by [RelativeCI](https://relative-ci.com/?utm_source=github&utm_campaign=github-action-summary)</sup>`,
  ];

  return output.join('\n\n');
}
